Example for https://restful-api.dev/ POST API.
EnriqueSoria/python-api-consumer pull request #4
Opened 2023-10-21 10:22 UTC by dukebody

Resolves https://github.com/EnriqueSoria/python-api-consumer/issues/3.

2023-10-21 10:23 UTC, dukebody commented
@EnriqueSoria No sé si está todo correcto o hay algo raro en el cliente. Me ha costado un poquitín doblegar algunos métodos para pasar los datos del POST en JSON. Ya me dices.

2023-10-21 10:23 UTC, dukebody commented
Ejemplo de uso:
```
from examples.random_post_api.client import ObjectsAPI

client = ObjectsAPI()
client.create_object(
    data={
            "name": "Apple MacBook Pro 16",
            "data": {
                "year": 2019,
                "price": 1849.99,
                "CPU model": "Intel Core i9",
                "Hard disk size": "1 TB"
        }
})
```

2023-10-23 07:04 UTC, EnriqueSoria requested changes

2023-10-23 07:04 UTC, EnriqueSoria commented on examples/random_post_api/endpoints.py
> +        return request
Como es muy habitual que las APIs hablen json quizás podríamos hacer que por defecto `RequestsEndpoint` use `json` en vez de `data`. O crear una clase `RequestsJsonEndpoint`

¿Qué opinas tu?

2023-10-23 07:04 UTC, EnriqueSoria commented on examples/random_post_api/models.py
> +# )
Se te ha colado este código comentado, ¿podrías borrarlo?

2023-10-27 14:04 UTC, dukebody commented on examples/random_post_api/endpoints.py
> +        return request
Creo que tienes razón. Actualizado.

2023-10-27 14:04 UTC, dukebody commented on examples/random_post_api/models.py
> +# )
Eliminado.

2023-10-28 11:16 UTC, EnriqueSoria approved these changes

2023-10-28 11:17 UTC, EnriqueSoria commented
Muchas gracias!! <3

2023-10-28 11:17 UTC, merged